# TODO(Matthias): review and see which exception we can remove over time.
# Eg removing syn is blocked by ark-ff-asm cutting a new release
# (https://github.com/arkworks-rs/algebra/issues/813) amongst other things.
allowed-duplicate-crates = [
  "dashu-base",
  "dashu-float",
  "dashu-int",
  "dashu-ratio",
  "generic-array",
  "itertools",
  "thiserror",
  "thiserror-impl",
  "regex-automata",
  "regex-syntax",
  "rand",
  "rand_chacha",
  "rand_core",
  "getrandom",
]
